---
- name: Common configuration for all servers
  hosts: all
  gather_facts: true
  become: yes
  vars:
    ansible_ssh_user: cloud-user
    ansible_ssh_private_key_file: ~/.ssh/test_id_rsa
  roles:
    - common

- name: Deploy Frontend Loadbalancer
  hosts: frontends
  become: true
  gather_facts: true
  vars:
    ansible_ssh_user: cloud-user
    ansible_ssh_private_key_file: ~/.ssh/test_id_rsa
  roles:
    - haproxy

- name: Deploy Tomcat on application servers
  hosts: apps
  become: true
  gather_facts: true
  vars:
    ansible_ssh_user: cloud-user
    ansible_ssh_private_key_file: ~/.ssh/test_id_rsa
  roles:
    - tomcat
    - tomcat-config

- name: Deploy DB backend
  hosts: appdbs
  gather_facts: true
  become: true
  vars:
    ansible_ssh_user: cloud-user
    ansible_ssh_private_key_file: ~/.ssh/test_id_rsa
  roles:
    - geerlingguy.postgresql
